export interface SampleOrder {
  id: bigint;
  status: string;
  boxType: string;
  qty: number;
  amount: number;
  date: string;
  customer: string;
  dimensions?: string;
  location?: string;
  customerCompany?: string;
  customerEmail?: string;
  customerPhone?: string;
  customerGST?: string;
  assignedTo?: string;
  state?: string;
  area?: string;
  paymentSubmitted?: boolean;
  paymentRef?: string;
}

export const SAMPLE_ORDERS: SampleOrder[] = [
  {
    id: 1n,
    status: "new",
    boxType: "Wooden Box",
    qty: 50,
    amount: 0,
    date: "2026-03-15",
    customer: "Sharma Industries",
    dimensions: "80 × 60 × 50 cm",
    location: "Pune, Maharashtra",
    customerCompany: "Sharma Industries Pvt Ltd",
    customerEmail: "orders@sharmaindustries.in",
    customerPhone: "+91 98200 11234",
    customerGST: "27AABCS1429B1ZB",
    state: "Maharashtra",
    area: "Pune West",
    paymentSubmitted: false,
  },
  {
    id: 2n,
    status: "assigned",
    boxType: "Plastic Box",
    qty: 200,
    amount: 0,
    date: "2026-03-18",
    customer: "TechCo Ltd",
    dimensions: "40 × 30 × 25 cm",
    location: "Bengaluru, Karnataka",
    customerCompany: "TechCo Manufacturing Ltd",
    customerEmail: "procurement@techco.co.in",
    customerPhone: "+91 80001 56789",
    customerGST: "29AABCT2310B1Z5",
    assignedTo: "Rahul Verma",
    state: "Karnataka",
    area: "Electronic City",
    paymentSubmitted: false,
  },
  {
    id: 3n,
    status: "quoted",
    boxType: "Industrial Custom",
    qty: 30,
    amount: 82000,
    date: "2026-03-20",
    customer: "BuildCo Industries",
    dimensions: "120 × 100 × 80 cm",
    location: "Ahmedabad, Gujarat",
    customerCompany: "BuildCo Infrastructure Ltd",
    customerEmail: "supply@buildco.in",
    customerPhone: "+91 79002 34567",
    customerGST: "24AABCB1234C1ZA",
    assignedTo: "Priya Patel",
    state: "Gujarat",
    area: "GIDC Naroda",
    paymentSubmitted: false,
  },
  {
    id: 4n,
    status: "accepted",
    boxType: "Wooden Box",
    qty: 100,
    amount: 42000,
    date: "2026-03-22",
    customer: "SupplyCo Global",
    dimensions: "60 × 40 × 35 cm",
    location: "Chennai, Tamil Nadu",
    customerCompany: "SupplyCo Global Pvt Ltd",
    customerEmail: "ops@supplycoglobal.com",
    customerPhone: "+91 44001 78901",
    customerGST: "33AABCS9876D1ZF",
    assignedTo: "Arjun Menon",
    state: "Tamil Nadu",
    area: "Ambattur Industrial Estate",
    paymentSubmitted: true,
    paymentRef: "HDFC/2026/REF/490211",
  },
  {
    id: 5n,
    status: "advanceVerified",
    boxType: "Plastic Box",
    qty: 75,
    amount: 18750,
    date: "2026-03-25",
    customer: "RetailCo Express",
    dimensions: "35 × 25 × 20 cm",
    location: "Hyderabad, Telangana",
    customerCompany: "RetailCo Express Ltd",
    customerEmail: "warehouse@retailcoexpress.in",
    customerPhone: "+91 40002 23456",
    customerGST: "36AABCR5432E1ZG",
    assignedTo: "Sneha Reddy",
    state: "Telangana",
    area: "Uppal Industrial Area",
    paymentSubmitted: false,
  },
  {
    id: 6n,
    status: "preparing",
    boxType: "Industrial Custom",
    qty: 20,
    amount: 64000,
    date: "2026-03-26",
    customer: "AutoParts India",
    dimensions: "150 × 120 × 100 cm",
    location: "Gurugram, Haryana",
    customerCompany: "AutoParts India Pvt Ltd",
    customerEmail: "logistics@autopartsindia.com",
    customerPhone: "+91 12400 67890",
    customerGST: "06AABCA7654F1ZH",
    assignedTo: "Vikram Singh",
    state: "Haryana",
    area: "IMT Manesar",
    paymentSubmitted: false,
  },
  {
    id: 7n,
    status: "inTransit",
    boxType: "Wooden Box",
    qty: 150,
    amount: 52500,
    date: "2026-03-28",
    customer: "PharmaLink",
    dimensions: "50 × 45 × 40 cm",
    location: "Mumbai, Maharashtra",
    customerCompany: "PharmaLink Healthcare Ltd",
    customerEmail: "supply@pharmalink.co.in",
    customerPhone: "+91 22003 45678",
    customerGST: "27AABCP3456G1ZI",
    assignedTo: "Rahul Verma",
    state: "Maharashtra",
    area: "Andheri East",
    paymentSubmitted: false,
  },
  {
    id: 8n,
    status: "delivered",
    boxType: "Plastic Box",
    qty: 300,
    amount: 27000,
    date: "2026-03-10",
    customer: "ElectraWorld",
    dimensions: "30 × 20 × 15 cm",
    location: "Jaipur, Rajasthan",
    customerCompany: "ElectraWorld Electronics",
    customerEmail: "purchase@electraworld.in",
    customerPhone: "+91 14100 89012",
    customerGST: "08AABCE6543H1ZJ",
    assignedTo: "Priya Patel",
    state: "Rajasthan",
    area: "Sitapura Industrial Area",
    paymentSubmitted: true,
    paymentRef: "ICICI/2026/REF/330541",
  },
  {
    id: 9n,
    status: "finalPaymentPending",
    boxType: "Industrial Custom",
    qty: 45,
    amount: 135000,
    date: "2026-03-08",
    customer: "LogiFreight",
    dimensions: "200 × 150 × 120 cm",
    location: "Delhi",
    customerCompany: "LogiFreight Solutions Pvt Ltd",
    customerEmail: "ops@logifreight.co.in",
    customerPhone: "+91 11002 12345",
    customerGST: "07AABCL4321I1ZK",
    assignedTo: "Arjun Menon",
    state: "Delhi",
    area: "Okhla Industrial Phase 2",
    paymentSubmitted: true,
    paymentRef: "SBI/2026/REF/118822",
  },
  {
    id: 10n,
    status: "completed",
    boxType: "Wooden Box",
    qty: 60,
    amount: 24000,
    date: "2026-02-28",
    customer: "GreenPack Co",
    dimensions: "70 × 55 × 45 cm",
    location: "Nagpur, Maharashtra",
    customerCompany: "GreenPack Co Pvt Ltd",
    customerEmail: "admin@greenpackco.in",
    customerPhone: "+91 71200 56789",
    customerGST: "27AABCG2109J1ZL",
    assignedTo: "Sneha Reddy",
    state: "Maharashtra",
    area: "MIDC Hingna",
    paymentSubmitted: false,
  },
];
