/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'user' : Principal,
  'description' : string,
  'timestamp' : Time,
}
export interface AdminProfile {
  'name' : string,
  'joinedAt' : Time,
  'isAdmin' : boolean,
}
export interface CustomerProfile {
  'name' : string,
  'joinedAt' : Time,
  'isActive' : boolean,
  'shippingAddress' : string,
}
export interface ItemRequest { 'description' : string, 'quantity' : bigint }
export interface LineItem {
  'description' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'customer' : Principal,
  'totalAmount' : bigint,
  'timestamp' : Time,
  'items' : Array<LineItem>,
  'assignedTeamMember' : [] | [Principal],
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'inProduction' : null } |
  { 'inReview' : null } |
  { 'delivered' : null } |
  { 'accepted' : null } |
  { 'quoted' : null };
export interface TeamMemberProfile {
  'name' : string,
  'joinedAt' : Time,
  'skills' : Array<string>,
}
export type Time = bigint;
export type UserProfile = { 'admin' : AdminProfile } |
  { 'customer' : CustomerProfile } |
  { 'teamMember' : TeamMemberProfile };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptQuote' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignTeamMember' : ActorMethod<[Principal, TeamMemberProfile], undefined>,
  'assignTeamMemberToOrder' : ActorMethod<[bigint, Principal], undefined>,
  'cancelOrder' : ActorMethod<[bigint], undefined>,
  'createAdminProfile' : ActorMethod<[AdminProfile], undefined>,
  'createProfile' : ActorMethod<[UserProfile], undefined>,
  'getActivityFeed' : ActorMethod<[], Array<Activity>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getAssignedOrders' : ActorMethod<[], Array<Order>>,
  'getCallerRole' : ActorMethod<[], UserRole>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerOrders' : ActorMethod<[Principal], Array<Order>>,
  'getOpenOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrderStats' : ActorMethod<
    [],
    {
      'shipped' : bigint,
      'totalOrders' : bigint,
      'cancelled' : bigint,
      'pending' : bigint,
      'inProduction' : bigint,
      'delivered' : bigint,
      'quoted' : bigint,
    }
  >,
  'getOwnOrders' : ActorMethod<[], Array<Order>>,
  'getUserActivities' : ActorMethod<[Principal], Array<Activity>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasTeamAccess' : ActorMethod<[], boolean>,
  'isAuthenticated' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitQuoteRequest' : ActorMethod<[Array<ItemRequest>], bigint>,
  'submitQuoteRequestForCustomer' : ActorMethod<
    [Principal, Array<ItemRequest>],
    bigint
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateQuotePrice' : ActorMethod<
    [bigint, Array<LineItem>, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];