/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const TeamMemberProfile = IDL.Record({
  'name' : IDL.Text,
  'joinedAt' : Time,
  'skills' : IDL.Vec(IDL.Text),
});
export const AdminProfile = IDL.Record({
  'name' : IDL.Text,
  'joinedAt' : Time,
  'isAdmin' : IDL.Bool,
});
export const CustomerProfile = IDL.Record({
  'name' : IDL.Text,
  'joinedAt' : Time,
  'isActive' : IDL.Bool,
  'shippingAddress' : IDL.Text,
});
export const UserProfile = IDL.Variant({
  'admin' : AdminProfile,
  'customer' : CustomerProfile,
  'teamMember' : TeamMemberProfile,
});
export const Activity = IDL.Record({
  'user' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : Time,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'inProduction' : IDL.Null,
  'inReview' : IDL.Null,
  'delivered' : IDL.Null,
  'accepted' : IDL.Null,
  'quoted' : IDL.Null,
});
export const LineItem = IDL.Record({
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'customer' : IDL.Principal,
  'totalAmount' : IDL.Nat,
  'timestamp' : Time,
  'items' : IDL.Vec(LineItem),
  'assignedTeamMember' : IDL.Opt(IDL.Principal),
});
export const ItemRequest = IDL.Record({
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptQuote' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignTeamMember' : IDL.Func([IDL.Principal, TeamMemberProfile], [], []),
  'assignTeamMemberToOrder' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'cancelOrder' : IDL.Func([IDL.Nat], [], []),
  'createAdminProfile' : IDL.Func([AdminProfile], [], []),
  'createProfile' : IDL.Func([UserProfile], [], []),
  'getActivityFeed' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAssignedOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getOpenOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrderStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'shipped' : IDL.Nat,
          'totalOrders' : IDL.Nat,
          'cancelled' : IDL.Nat,
          'pending' : IDL.Nat,
          'inProduction' : IDL.Nat,
          'delivered' : IDL.Nat,
          'quoted' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getOwnOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getUserActivities' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Activity)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasTeamAccess' : IDL.Func([], [IDL.Bool], ['query']),
  'isAuthenticated' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitQuoteRequest' : IDL.Func([IDL.Vec(ItemRequest)], [IDL.Nat], []),
  'submitQuoteRequestForCustomer' : IDL.Func(
      [IDL.Principal, IDL.Vec(ItemRequest)],
      [IDL.Nat],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateQuotePrice' : IDL.Func([IDL.Nat, IDL.Vec(LineItem), IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const TeamMemberProfile = IDL.Record({
    'name' : IDL.Text,
    'joinedAt' : Time,
    'skills' : IDL.Vec(IDL.Text),
  });
  const AdminProfile = IDL.Record({
    'name' : IDL.Text,
    'joinedAt' : Time,
    'isAdmin' : IDL.Bool,
  });
  const CustomerProfile = IDL.Record({
    'name' : IDL.Text,
    'joinedAt' : Time,
    'isActive' : IDL.Bool,
    'shippingAddress' : IDL.Text,
  });
  const UserProfile = IDL.Variant({
    'admin' : AdminProfile,
    'customer' : CustomerProfile,
    'teamMember' : TeamMemberProfile,
  });
  const Activity = IDL.Record({
    'user' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : Time,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'inProduction' : IDL.Null,
    'inReview' : IDL.Null,
    'delivered' : IDL.Null,
    'accepted' : IDL.Null,
    'quoted' : IDL.Null,
  });
  const LineItem = IDL.Record({
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'customer' : IDL.Principal,
    'totalAmount' : IDL.Nat,
    'timestamp' : Time,
    'items' : IDL.Vec(LineItem),
    'assignedTeamMember' : IDL.Opt(IDL.Principal),
  });
  const ItemRequest = IDL.Record({
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptQuote' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignTeamMember' : IDL.Func([IDL.Principal, TeamMemberProfile], [], []),
    'assignTeamMemberToOrder' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'cancelOrder' : IDL.Func([IDL.Nat], [], []),
    'createAdminProfile' : IDL.Func([AdminProfile], [], []),
    'createProfile' : IDL.Func([UserProfile], [], []),
    'getActivityFeed' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAssignedOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerOrders' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getOpenOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrderStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'shipped' : IDL.Nat,
            'totalOrders' : IDL.Nat,
            'cancelled' : IDL.Nat,
            'pending' : IDL.Nat,
            'inProduction' : IDL.Nat,
            'delivered' : IDL.Nat,
            'quoted' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getOwnOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getUserActivities' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Activity)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasTeamAccess' : IDL.Func([], [IDL.Bool], ['query']),
    'isAuthenticated' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitQuoteRequest' : IDL.Func([IDL.Vec(ItemRequest)], [IDL.Nat], []),
    'submitQuoteRequestForCustomer' : IDL.Func(
        [IDL.Principal, IDL.Vec(ItemRequest)],
        [IDL.Nat],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateQuotePrice' : IDL.Func(
        [IDL.Nat, IDL.Vec(LineItem), IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };